### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/developer-report#1]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/developer-report/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by emceeaich** [comment]
I don't have configuration access to this repo. I'll need to be added as a maintainer.

**Comment by ghost** [comment]
*Poof* you're an admin (wiki settings are okay). Thanks for the followup.
